spring:
  application:
    name: movie-manager

server:
  port: 5000
  servlet:
    context-path: /movie-manager

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/${MYSQL_DB}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  # 连接池
  hikari:
    #连接池名
    pool-name: DateHikariCP
    #最小空闲连接数
    minimum-idle: 5
    # 空闲连接存活最大时间，默认600000（10分钟）
    idle-timeout: 180000
    # 连接池最大连接数，默认是10
    maximum-pool-size: 10
    # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    max-lifetime: 1800000
    # 数据库连接超时时间,默认30秒，即30000
    connection-timeout: 30000
    connection-test-query: SELECT 1

spark:
  home: '${SPARK_HOME}'
  master: '${SPARK_MASTER}'
  task-jar: '${PROJECT_HOME}/build/libs/tasks-all.jar'
  result-base: '/movie-manage/results/'

init.path: '${PROJECT_HOME}/ml-latest/'